title: horizOn Changelog
description: Public changelog for the horizOn platform by ProjectMakers
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

exclude:
  - README.md
  - LICENSE
