title: horizOn Changelog
description: Public changelog for the horizOn platform by ProjectMakers
url: https://projectmakersde.github.io
baseurl: /horizOn-Changelog

plugins: []

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
